In [1]:
import numpy as np

# 1

In [2]:
def alexandre_matrix(iterable,max_pow,increasing=False):
    x=np.array(iterable)
    if increasing==False:
        y=np.column_stack([x**(max_pow-1-i) for i in range(max_pow)])
    else:
        y=np.column_stack([x**(i) for i in range(max_pow)])
    return y

alexandre_matrix([1,2,3,4,5],4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]], dtype=int32)

In [3]:
alexandre_matrix([1,2,3,4,5],4,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]], dtype=int32)

# 2

In [4]:
def moving_avg(iterable,window):
    x=np.array(iterable)
    y=np.cumsum(x)
    y[window:]=y[window:]-y[:-window]
    return y[window-1:]/window

moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])